### ISSUE TITLE
Use Debian as base image

### ISSUE THREAD

**Issue by sammcj** [dockerana/dockerana#34]
It may be worth switching the base image from Ubuntu to Debian.

Generally Debian's packages are a lot more thoroughly tested than Ubuntu and the base image is significantly smaller.

**Comment by cglewis** [comment]
@sammcj thanks for the suggestion, I have updated most of the containers to use Debian, but a couple still are not, due to a few build failures, I will need to do some more testing on that before those containers are moved over.  Feel free to open a PR though, if you have a working setup.  Thanks!
